### ISSUE TITLE
재치 채팅 팝업UI 

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#119]
## 💡 issue
재치 채팅 팝업UI 

## 📝 todo
- [x]  차단 팝업
- [ ]  신고 팝업
- [x]  약속 알림 허용 팝업
- [ ]  약속 등록 팝업
- [ ]  약속 수정 팝업
