### ISSUE TITLE
재치 등록 조건 부합X 케이스 팝업 

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#127]
## 💡 issue
재치 등록 조건 부합X 케이스 팝업 

## 📝 todo
- [x] 카테고리 미선택
- [x] 상품 이름 미등록
    - [x] UITextField delegate 메서드 구현
- [x] 이미지 최소 1장 
- [x] 구매일자 -> 음식 카테고리만 필수 
- [x] 유통기한 -> 음식 카테고리만 필수
- [x] 재치등록 여부
