### ISSUE TITLE
재치 등록 VC, View 파일 분리

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#128]
## 💡 issue
재치 등록 VC, View 파일 분리

## 📝 todo
- [x]  FirstRegister 파일 분리
- [x]  SecondRegister 파일 분리
- [x]  CheckRegister 파일 분리
