### ISSUE TITLE
가치 채팅 UI

### ISSUE THREAD

**Issue by gom1n** [Zatch-Team/Zatch_iOS#152]
## 💡 issue
가치 채팅 부분 작업합니다.

## 📝 todo
- [ ]  채팅리스트 구분 - 재치/가치
- [ ]  가치 채팅 - 팝업창 (3)
- [ ]  가치 채팅화면 - 채팅 부분
- [ ]  가치 채팅화면 - (+) 클릭 시 하단뷰 작업
- [ ]  가치 채팅화면 - 더보기 클릭 시 스와이프 화면 
- [ ]  가치 채팅 - 사용자 차단/내보내기 팝업 (2)
- [ ]  가치 채팅 - 입금 하단 팝업 (3)
- [ ]  가치 채팅화면 - 상단 공지사항
- [ ]  가치 채팅 - 입금 확인/ 입금 관리 / 수정

양이 방대하다..
