### ISSUE TITLE
재치 검색 iOS 버전 UI 적용 및 RxSwift 적용 리팩토링

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#176]
## 💡 issue
재치 검색 iOS 버전 UI 적용 및 RxSwift 적용 리팩토링

## 📝 todo
- [ ] Util 클래스로 SearchRequestManager 생성 
- [x] iOS 버전 UI 변경
- [ ] 스토리보드 참고해 세부 기능 점검
