### ISSUE TITLE
TableOnlyView 생성 통한 View 재사용

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#198]
## 💡 issue
TableOnlyView 생성 통한 View 재사용

+ UI 중 TableView만 사용하는 View들이 꽤 많이 있음
+ 이 경우에 TableView에 register하는 Cell만 다르게 설정하면 되므로 공통 View 파일을 하나 만들어 재사용하고자 함

## 📝 todo
- [x]  TableOnlyView 클래스 생성
- [x]  register 설정 메서드 구현
- [x]  기존 적용 클래스들 대체
