### ISSUE TITLE
MapViewController Protocol + 상속 활용 재설계

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#212]
## 💡 issue
MapViewController Protocol + 상속 활용 재설계

## 📝 todo
- [x] 재사용 목적 MapViewController 클래스 설계
- [x] Map Protocol 설계 
- [x] 동네 설정 클래스 재설계
- [x] 약속잡기 클래스 재설계
