### ISSUE TITLE
마이페이지 고객센터(FAQ) UI 구현 및 json 파일 통한 데이터 바인딩

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#225]
## 💡 issue
마이페이지 FAQ UI 구현 및 json 파일 통한 데이터 추가

## 📝 todo
- [x]  UI 재구현(TabMan 라이브러리 제거)
- [x]  FAQ 데이터 정리
- [x]  FAQ 데이터 바인딩
