### ISSUE TITLE
동네인증 UI 및 카카오 API 통한 기능 구현

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#43]
## 💡 issue
회원가입 이후 진행되는 동네 인증 기능으로, 
카카오 지도 API 통한 현재 위치 제공 및 동네 설정 기능 구현 예정

## 📝 todo
- [x]  카카오 지도 API 연결
- [x]  마커 표시한 장소에 대해서 '동' 정보만 가져오기
- [x]  위치 액세스
- [x]  동네 인증 UI 구현
- [x]  현재 위치 정보 통한 동네 인증 기능 추가
- [x]  동네인증 법정동(?) 기준으로 설정 -> 기획팀이 픽스하면 마저 진행
