### ISSUE TITLE
MapAlert 약속장소 잡기, 동네 설정 2가지로 자식 파일 나누기

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#55]
## 💡 issue
MapAlert의 경우 지도 View가 나타나는 약속 장소 잡기, 동네 설정 2개의 VC에서 사용됨.
UI는 거의 유사하지만 기능의 차이가 있기 때문에 자식 Alert 파일 나눠서 각각 구현하기.

## 📝 todo
- [ ]  MapAlert 하위 클래스 설계
- [ ]  MapAlert 파일 나누기
- [ ]  MapAlert  자식 클래스들 각각 기능 구현
