### ISSUE TITLE
마이페이지 설정 UI 및 기능 구현 

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#66]
## 💡 issue
마이페이지 설정 UI 및 기능 구현

## 📝 todo
- [x]  마이페이지 설정 - 파일 추가
- [x]  마이페이지 설정 UI 구현
- [ ]  마이페이지 설정 기능 구현
