### ISSUE TITLE
내 프로필 편집 UI 구현

### ISSUE THREAD

**Issue by gom1n** [Zatch-Team/Zatch_iOS#68]
## 💡 issue
내 프로필 편집 페이지의 UI를 구현합니다.

## 📝 todo
- [x]  TextField 커스텀
- [x] 특정 문자열의 색상을 바꿈
- [x] 30일 이용 제한 팝업
- [x] 최근 변경일 라벨 띄우기
- [x] 앨범 선택 기능
