### ISSUE TITLE
재치 등록 상속 관계 정리

### ISSUE THREAD

**Issue by dev-muuu** [Zatch-Team/Zatch_iOS#79]
## 💡 issue
재치 등록 나눔 기능 구현하기 
이때 재치 등록 기본 케이스와 UI 거의 유사하기 때문에, 공통 소스 만들고, 상속 받아 정보 부분만 각각 구현할 수 있도록 함

## 📝 todo
- [x] 재치 등록 상속 관계 정리
- [x] 재치 등록 부모, 자식 파일 생성
- [x] 상속관계에 따른 프로퍼티 등 코드 리팩토링
