### ISSUE TITLE
메인 페이지 UI 구현

### ISSUE THREAD

**Issue by gom1n** [Zatch-Team/Zatch_iOS#9]
## 💡 issue
메인페이지 UI를 구현하되, Code-base로 작업합니다.

## 📝 todo
- [x]  메인 페이지 테이블뷰
- [ ] ~~관심동네 팝업~~
- [x] 동네 변경 기능
- [x] 하트 클릭 시 상태 변경
